/*=============================================================================
 Copyright 1998-2007 Epic Games, Inc. All Rights Reserved.
=============================================================================*/
#if USE_D3D_RHI

// Temporary vertex for utility class
#pragma pack(push, 1)
struct FUtilVertex
{
	FVector   Position;
	FVector2D UVs[4];
	FColor	  Color;
	FColor    SmoothingMask;
};

#pragma pack(pop)

/**
*
* This utility class builds on D3DX functionality.
* Used for editor helpers.
*
*/
class FD3DMeshUtilities
{

private:

	/**
	* ConstructD3DVertexElement - acts as a constructor for D3DVERTEXELEMENT9
	*/
	D3DVERTEXELEMENT9 ConstructD3DVertexElement(WORD Stream, WORD Offset, BYTE Type, BYTE Method, BYTE Usage, BYTE UsageIndex);

	/**
	* Creates a D3DXMESH from a FStaticMeshRenderData
	* @param SourceMesh Mesh to extract from
	* @param D3DMesh Mesh to create
	* @return Boolean representing success or failure
	*/
	UBOOL ConvertUMeshToD3DXMesh(FStaticMeshRenderData& SourceMesh, LPD3DXMESH& D3DMesh);

	/**
	* Creates a FStaticMeshRenderData from a D3DXMesh
	* @param DestMesh Destination mesh to extract to
	* @param NumUVs Number of UVs
	* @param Elements Elements array
	* @return Boolean representing success or failure
	*/
	UBOOL ConvertD3DXMeshToUMesh(
		LPD3DXMESH& D3DMesh, 
		FStaticMeshRenderData& DestMesh, 
		INT NumUVs, 
		TArray<FStaticMeshElement>& Elements, 
		UBOOL bClearDestElements);

public:

	FD3DMeshUtilities() {}

	/**
	 * Generates a simplified LOD from a static mesh
	 * @param StaticMesh - The input/output mesh
	 * @param DesiredLOD - The LOD level to generate the simplified mesh for
	 * @param DesiredTriangles - The desired triangle count for the LOD. Resulting triangle count may not be desired triangle count.
	 * @return TRUE if successful
	 */
	UBOOL GenerateLOD(UStaticMesh* StaticMesh, INT DesiredLOD, INT DesiredTriangles);

	/**
	* Generates a unique UV layout for a static mesh
	* @param StaticMesh - The input/output mesh
	* @param LODIndex - The LOD level
	* @param TexCoordIndex - Index of the uv channel to overwrite or create
	* @param MaxDesiredStretch - The amount of stretching allowed. 0 means no stretching is allowed, 1 means any amount of stretching can be used. 
	* @param ChartsGenerated - Number of charts generated by the uv unwrap algorithm.
	* @return TRUE if successful
	*/
	UBOOL GenerateUVs(UStaticMesh* StaticMesh, UINT LODIndex, UINT TexCoordIndex, FLOAT &MaxDesiredStretch, UINT &ChartsGenerated);
};

#endif

