/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)


#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName ONLINESUBSYSTEMPC_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(OnFlushOnlineStatsComplete)
AUTOGENERATE_NAME(OnFriendsChange)
AUTOGENERATE_NAME(OnLoginCancelled)
AUTOGENERATE_NAME(OnLoginChange)
AUTOGENERATE_NAME(OnMutingChange)
AUTOGENERATE_NAME(OnPlayerTalking)
AUTOGENERATE_NAME(OnReadFriendsComplete)
AUTOGENERATE_NAME(OnReadOnlineStatsComplete)
AUTOGENERATE_NAME(OnReadProfileSettingsComplete)
AUTOGENERATE_NAME(OnRecognitionComplete)
AUTOGENERATE_NAME(OnWriteProfileSettingsComplete)

#ifndef NAMES_ONLY

struct OnlineSubsystemPC_eventOnFlushOnlineStatsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnFlushOnlineStatsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnReadOnlineStatsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnReadOnlineStatsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnRecognitionComplete_Parms
{
    OnlineSubsystemPC_eventOnRecognitionComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnPlayerTalking_Parms
{
    struct FUniqueNetId Player;
    OnlineSubsystemPC_eventOnPlayerTalking_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnReadFriendsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnReadFriendsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnWriteProfileSettingsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnWriteProfileSettingsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnReadProfileSettingsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnReadProfileSettingsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnFriendsChange_Parms
{
    OnlineSubsystemPC_eventOnFriendsChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnMutingChange_Parms
{
    OnlineSubsystemPC_eventOnMutingChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnLoginCancelled_Parms
{
    OnlineSubsystemPC_eventOnLoginCancelled_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnLoginChange_Parms
{
    OnlineSubsystemPC_eventOnLoginChange_Parms(EEventParm)
    {
    }
};
class UOnlineSubsystemPC : public UOnlineSubsystemCommonImpl
{
public:
    //## BEGIN PROPS OnlineSubsystemPC
    FStringNoInit LoggedInPlayerName;
    struct FUniqueNetId LoggedInPlayerId;
    TArrayNoInit<FOnlineAsyncTaskPC*> AsyncTasks;
    FStringNoInit ProfileDataDirectory;
    FStringNoInit ProfileDataExtension;
    TArrayNoInit<FScriptDelegate> ReadProfileSettingsDelegates;
    TArrayNoInit<FScriptDelegate> WriteProfileSettingsDelegates;
    class UOnlineProfileSettings* CachedProfile;
    TArrayNoInit<FScriptDelegate> SpeechRecognitionCompleteDelegates;
    TArrayNoInit<FScriptDelegate> ReadFriendsDelegates;
    TArrayNoInit<FScriptDelegate> FriendsChangeDelegates;
    TArrayNoInit<FScriptDelegate> MutingChangeDelegates;
    FScriptDelegate __OnLoginChange__Delegate;
    FScriptDelegate __OnLoginCancelled__Delegate;
    FScriptDelegate __OnMutingChange__Delegate;
    FScriptDelegate __OnFriendsChange__Delegate;
    FScriptDelegate __OnReadProfileSettingsComplete__Delegate;
    FScriptDelegate __OnWriteProfileSettingsComplete__Delegate;
    FScriptDelegate __OnReadFriendsComplete__Delegate;
    FScriptDelegate __OnPlayerTalking__Delegate;
    FScriptDelegate __OnRecognitionComplete__Delegate;
    FScriptDelegate __OnReadOnlineStatsComplete__Delegate;
    FScriptDelegate __OnFlushOnlineStatsComplete__Delegate;
    //## END PROPS OnlineSubsystemPC

    virtual UBOOL Init();
    virtual UBOOL ReadProfileSettings(BYTE LocalUserNum,class UOnlineProfileSettings* ProfileSettings);
    virtual UBOOL WriteProfileSettings(BYTE LocalUserNum,class UOnlineProfileSettings* ProfileSettings);
    DECLARE_FUNCTION(execInit)
    {
        P_FINISH;
        *(UBOOL*)Result=Init();
    }
    DECLARE_FUNCTION(execReadProfileSettings)
    {
        P_GET_BYTE(LocalUserNum);
        P_GET_OBJECT(UOnlineProfileSettings,ProfileSettings);
        P_FINISH;
        *(UBOOL*)Result=ReadProfileSettings(LocalUserNum,ProfileSettings);
    }
    DECLARE_FUNCTION(execWriteProfileSettings)
    {
        P_GET_BYTE(LocalUserNum);
        P_GET_OBJECT(UOnlineProfileSettings,ProfileSettings);
        P_FINISH;
        *(UBOOL*)Result=WriteProfileSettings(LocalUserNum,ProfileSettings);
    }
    void delegateOnFlushOnlineStatsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnFlushOnlineStatsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnFlushOnlineStatsComplete,&__OnFlushOnlineStatsComplete__Delegate,&Parms);
    }
    void delegateOnReadOnlineStatsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnReadOnlineStatsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnReadOnlineStatsComplete,&__OnReadOnlineStatsComplete__Delegate,&Parms);
    }
    void delegateOnRecognitionComplete()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnRecognitionComplete,&__OnRecognitionComplete__Delegate,NULL);
    }
    void delegateOnPlayerTalking(struct FUniqueNetId Player)
    {
        OnlineSubsystemPC_eventOnPlayerTalking_Parms Parms(EC_EventParm);
        Parms.Player=Player;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnPlayerTalking,&__OnPlayerTalking__Delegate,&Parms);
    }
    void delegateOnReadFriendsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnReadFriendsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnReadFriendsComplete,&__OnReadFriendsComplete__Delegate,&Parms);
    }
    void delegateOnWriteProfileSettingsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnWriteProfileSettingsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnWriteProfileSettingsComplete,&__OnWriteProfileSettingsComplete__Delegate,&Parms);
    }
    void delegateOnReadProfileSettingsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnReadProfileSettingsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnReadProfileSettingsComplete,&__OnReadProfileSettingsComplete__Delegate,&Parms);
    }
    void delegateOnFriendsChange()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnFriendsChange,&__OnFriendsChange__Delegate,NULL);
    }
    void delegateOnMutingChange()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnMutingChange,&__OnMutingChange__Delegate,NULL);
    }
    void delegateOnLoginCancelled()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnLoginCancelled,&__OnLoginCancelled__Delegate,NULL);
    }
    void delegateOnLoginChange()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnLoginChange,&__OnLoginChange__Delegate,NULL);
    }
    DECLARE_CLASS(UOnlineSubsystemPC,UOnlineSubsystemCommonImpl,0|CLASS_Config,OnlineSubsystemPC)
    #include "UOnlineSubsystemPC.h"
};

#endif

AUTOGENERATE_FUNCTION(UOnlineSubsystemPC,-1,execWriteProfileSettings);
AUTOGENERATE_FUNCTION(UOnlineSubsystemPC,-1,execReadProfileSettings);
AUTOGENERATE_FUNCTION(UOnlineSubsystemPC,-1,execInit);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef ONLINESUBSYSTEMPC_NATIVE_DEFS
#define ONLINESUBSYSTEMPC_NATIVE_DEFS

DECLARE_NATIVE_TYPE(OnlineSubsystemPC,UOnlineSubsystemPC);

#define AUTO_INITIALIZE_REGISTRANTS_ONLINESUBSYSTEMPC \
	UOnlineSubsystemPC::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindOnlineSubsystemPCUOnlineSubsystemPCNative; \

#endif // ONLINESUBSYSTEMPC_NATIVE_DEFS

#ifdef NATIVES_ONLY
NATIVE_INFO(UOnlineSubsystemPC) GOnlineSubsystemPCUOnlineSubsystemPCNatives[] = 
{ 
	MAP_NATIVE(UOnlineSubsystemPC,execWriteProfileSettings)
	MAP_NATIVE(UOnlineSubsystemPC,execReadProfileSettings)
	MAP_NATIVE(UOnlineSubsystemPC,execInit)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(OnlineSubsystemPC,UOnlineSubsystemPC);

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(U,OnlineSubsystemPC,LoggedInPlayerName)
VERIFY_CLASS_OFFSET_NODIE(U,OnlineSubsystemPC,__OnFlushOnlineStatsComplete__Delegate)
VERIFY_CLASS_SIZE_NODIE(UOnlineSubsystemPC)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY
