/*=============================================================================
	UExporter.cpp: Exporter class definition.
	Copyright 1998-2007 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

/**
 * Encapsulates a map form objects to their direct inners, used by UExporter::ExportObjectInner when exporting objects.
 * Should be recreated before new objects are created within objects that are to be exported!
 *
 * Typical usage pattern is:
 *
 *     const FExportObjectInnerContext Context;
 *     foreach( Object in a set of objects)
 *         Exporter->ExportObjectInner( Context, Object );
 */
class FExportObjectInnerContext
{
public:
	/**
	 * Creates the map from objects to their direct inners.
	 */
	FExportObjectInnerContext();

private:
	friend class UExporter;

	/** Data structure used to map an object to its inners. */
	typedef TArray<UObject*>			InnerList;
	typedef TMap<UObject*,InnerList>	ObjectToInnerMapType;

	ObjectToInnerMapType				ObjectToInnerMap;
};

/**
 * An object responsible for exporting other objects to archives (files).
 */
class UExporter : public UObject
{
	DECLARE_ABSTRACT_CLASS(UExporter,UObject,CLASS_Transient|CLASS_Intrinsic,Core)

	// Variables.
	UClass*						SupportedClass;
	TArray<FString> 			FormatExtension;
	TArray<FString> 			FormatDescription;
	/** Index into FormatExtension/FormatDescription of the preferred export format. */
	INT							PreferredFormatIndex;
	INT							TextIndent;
	BITFIELD					bText			: 1;
	BITFIELD					bSelectedOnly	: 1;

	static FString	CurrentFilename;

	// Constructor.
	UExporter();

	// UObject interface.
	void Serialize( FArchive& Ar );
	void StaticConstructor();

	// UExporter interface.
	virtual UBOOL ExportText( const FExportObjectInnerContext* Context, UObject* Object, const TCHAR* Type, FOutputDevice& Ar, FFeedbackContext* Warn, DWORD PortFlags=0 ) { return( FALSE );}
	virtual UBOOL ExportBinary( UObject* Object, const TCHAR* Type, FArchive& Ar, FFeedbackContext* Warn, INT FileIndex = 0, DWORD PortFlags=0 ) { return( FALSE );}

	/** 
	 * Number of binary files to export for this object. Should be 1 in the vast majority of cases. Noted exception would be multichannel sounds
	 * which have upto 8 raw waves stored within them.
	 */
	virtual INT GetFileCount( void ) const { return( 1 ); }

	/** 
	 * Differentiates the filename for objects with multiple files to export. Only needs to be overridden if GetFileCount() returns > 1.
	 */
	virtual FString GetUniqueFilename( const TCHAR* Filename, INT FileIndex ) { check( FileIndex == 0 ); return( FString( Filename ) ); }

	static UExporter* FindExporter( UObject* Object, const TCHAR* Filetype );
	static INT ExportToFile( UObject* Object, UExporter* Exporter, const TCHAR* Filename, UBOOL InSelectedOnly, UBOOL NoReplaceIdentical=FALSE, UBOOL Prompt=FALSE );
	static UBOOL ExportToArchive( UObject* Object, UExporter* Exporter, FArchive& Ar, const TCHAR* FileType, INT FileIndex );
	static void ExportToOutputDevice( const FExportObjectInnerContext* Context, UObject* Object, UExporter* Exporter, FOutputDevice& Out, const TCHAR* FileType, INT Indent, DWORD PortFlags=0, UBOOL bInSelectedOnly=FALSE );

	/**
	 * Single entry point to export an object's subobjects, its components, and its properties
	 *
	 * @param Context			Context from which the set of 'inner' objects is extracted.  If NULL, an object iterator will be used.
	 * @param Object			The object to export 
	 * @param Ar				OutputDevice to print to
	 * @param PortFlags			Flags controlling export behavior
	 * @param bSkipComponents	TRUE if components should not be exported
	 */
	void ExportObjectInner(const FExportObjectInnerContext* Context, UObject* Object, FOutputDevice& Ar, DWORD PortFlags, UBOOL bSkipComponents=FALSE);

protected:
	/**
	 * Exports subobject definitions for all components specified.  Makes sure that components which are referenced
	 * by other components in the map are exported first.
	 *
	 * @param	Components		the components to export.  This map is typically generated by calling CollectComponents on the object being exported
	 * @param	Ar				the archive to output the subobject definitions to...usually the same archive that you're exporting the rest of the properties
	 * @param	PortFlags		the flags that were passed into the call to ExportText
	 */
	void ExportComponentDefinitions(const FExportObjectInnerContext* Context, TArray<UComponent*> Components, FOutputDevice& Ar, DWORD PortFlags);
};
